indexer_check_get:
    path: /indexer/check/get/*
    defaults: { _controller: IndexerBundle:Check:get }
    requirements: { _resource: indexer }

indexer_check_set:
    path: /indexer/check/set/*
    defaults: { _controller: IndexerBundle:Check:set }
    requirements: { _resource: indexer }

indexer_check:
    path: /indexer/check/check/*
    defaults: { _controller: IndexerBundle:Check:check }
    requirements: { _resource: indexer }

indexer_search:
    path: /indexer/search/*
    defaults: { _controller: IndexerBundle:Check:search }
    requirements: { _resource: indexer }
