parameters:
    indexer.result_sorter.relevance.compare_field: ~
    indexer.result_sorter.relevance.case_sensitive: ~

services:
    indexer.documentfieldnamefilter.camelcasetounderscore:
        class: Zend_Filter_Word_CamelCaseToUnderscore

    indexer.documentfieldnamefilter.stringtolower:
        class: Zend_Filter_StringToLower

    indexer.documentfieldnamefilter:
        class: Zend_Filter
        calls:
            - ["addFilter", ["@indexer.documentfieldnamefilter.camelcasetounderscore"]]
            - ["addFilter", ["@indexer.documentfieldnamefilter.stringtolower"]]

    indexer.documentfactory:
        class: Phlexible\IndexerBundle\Document\DocumentFactory
        arguments: ["@event_dispatcher", "@indexer.documentfieldnamefilter"]

    indexer.search:
        class: Phlexible\IndexerBundle\Search\Search

    indexer.query.parser:
        class: Phlexible\IndexerBundle\Query\QueryParser

    indexer.result.sorter.relevance:
        class: Phlexible\IndexerBundle\Result\Sorter\RelevanceSorter

    indexer.result.sorter.relevance.reverse:
        class: Phlexible\IndexerBundle\Result\Sorter\RelevanceReverseSorter

    indexer.result.sorter.field:
        class: Phlexible\IndexerBundle\Result\Sorter\FieldSorter
        arguments:
            - "%indexer.result_sorter.relevance.compare_field%"
            - "%indexer.result_sorter.relevance.case_sensitive%"

    indexer.result.sorter.field.reverse:
        class: Phlexible\IndexerBundle\Result\Sorter\FieldReverseSorter
        arguments: ["%indexer.result_sorter.relevance.compare_field%"]

    indexer.result:
        class: Phlexible\IndexerBundle\Result\Result
        arguments: ["@indexer.result.sorter.relevance"]

    indexer.query:
        class: Phlexible\IndexerBundle\Query\Query
        arguments: ["@indexer.query.parser", "@indexer.boost"]

    indexer.boost:
        class: Phlexible\IndexerBundle\Boost\Boost

    indexer.indexers:
        class: Phlexible\IndexerBundle\Indexer\IndexerCollection
        arguments: [[]]

    indexer.storages:
        class: Phlexible\IndexerBundle\Storage\StorageCollection
        arguments: [[]]

    # acl providers
    indexer.acl_provider:
        class: Phlexible\IndexerBundle\Acl\IndexerAclProvider
        tags:
            - {name: "security.acl.provider"}

    # asset providers
    indexer.asset_provider:
        class: Phlexible\IndexerBundle\AssetProvider\IndexerAssetProvider
        arguments: [@file_locator]
        tags:
            - {name: "asset.provider"}

    # problem checks
    indexer.query.checker:
        class: Phlexible\IndexerBundle\ProblemChecker\QueryChecker
        arguments: ["@indexer.search", "@properties"]
        tags:
            - {name: "problem.checker"}
