parameters:
    phlexible_indexer.result_sorter.relevance.compare_field: ~
    phlexible_indexer.result_sorter.relevance.case_sensitive: ~

services:
    phlexible_indexer.storage_operator:
        class: Phlexible\Bundle\IndexerBundle\Storage\Operation\Operator
        arguments: [@phlexible_queue.job_manager, @event_dispatcher]

    phlexible_indexer.document_field_name_filter.camelcasetounderscore:
        class: Zend_Filter_Word_CamelCaseToUnderscore

    phlexible_indexer.document_field_name_filter.stringtolower:
        class: Zend_Filter_StringToLower

    phlexible_indexer.document_field_name_filter:
        class: Zend_Filter
        calls:
            - [addFilter, [@phlexible_indexer.document_field_name_filter.camelcasetounderscore]]
            - [addFilter, [@phlexible_indexer.document_field_name_filter.stringtolower]]

    phlexible_indexer.document_factory:
        class: Phlexible\Bundle\IndexerBundle\Document\DocumentFactory
        arguments: [@event_dispatcher, @phlexible_indexer.document_field_name_filter]

    phlexible_indexer.indexers:
        class: Phlexible\Bundle\IndexerBundle\Indexer\IndexerCollection
        arguments: [[]]

    # problem checks
    phlexible_indexer.query.checker:
        class: Phlexible\Bundle\IndexerBundle\ProblemChecker\QueryChecker
        public: false
        arguments: [@phlexible_indexer.search, @properties]
        tags:
            - {name: phlexible_problem.problem_checker}

    # role providers
    phlexible_indexer.acl_provider:
        class: Phlexible\Bundle\IndexerBundle\RoleProvider\IndexerRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
