parameters:
    indexer.result_sorter.relevance.compare_field: ~
    indexer.result_sorter.relevance.case_sensitive: ~

services:
    indexer.documentfieldnamefilter.camelcasetounderscore:
        class: Zend_Filter_Word_CamelCaseToUnderscore

    indexer.documentfieldnamefilter.stringtolower:
        class: Zend_Filter_StringToLower

    indexer.documentfieldnamefilter:
        class: Zend_Filter
        calls:
            - ["addFilter", ["@indexer.documentfieldnamefilter.camelcasetounderscore"]]
            - ["addFilter", ["@indexer.documentfieldnamefilter.stringtolower"]]

    indexer.documentfactory:
        class: Phlexible\IndexerComponent\Document\DocumentFactory
        arguments: ["@event_dispatcher", "@indexer.documentfieldnamefilter"]

    indexer.tools:
        class: Phlexible\IndexerComponent\IndexerTools
        arguments: ["%kernel.bundles%", "@indexer.storages"]

    indexer.search:
        class: Phlexible\IndexerComponent\Search\Search
        arguments: ["@indexer.tools", "@indexer.result"]

    indexer.query.parser:
        class: Phlexible\IndexerComponent\Query\QueryParser

    indexer.result.sorter.relevance:
        class: Phlexible\IndexerComponent\Result\Sorter\RelevanceSorter

    indexer.result.sorter.relevance.reverse:
        class: Phlexible\IndexerComponent\Result\Sorter\RelevanceReverseSorter

    indexer.result.sorter.field:
        class: Phlexible\IndexerComponent\Result\Sorter\FieldSorter
        arguments:
            - "%indexer.result_sorter.relevance.compare_field%"
            - "%indexer.result_sorter.relevance.case_sensitive%"

    indexer.result.sorter.field.reverse:
        class: Phlexible\IndexerComponent\Result\Sorter\FieldReverseSorter
        arguments: ["%indexer.result_sorter.relevance.compare_field%"]

    indexer.result:
        class: Phlexible\IndexerComponent\Result\Result
        arguments: ["@indexer.result.sorter.relevance"]

    indexer.query:
        class: Phlexible\IndexerComponent\Query\Query
        arguments: ["@indexer.query.parser", "@indexer.boost"]

    indexer.boost:
        class: Phlexible\IndexerComponent\Boost\Boost

    indexer.indexers:
        class: Phlexible\IndexerComponent\Indexer\IndexerCollection
        arguments: [[]]

    indexer.storages:
        class: Phlexible\IndexerComponent\Storage\StorageCollection
        arguments: [[]]

    # acl provider
    indexer.acl_provider:
        class: Phlexible\IndexerComponent\Acl\IndexerAclProvider
        tags:
            - {name: "security.acl.provider"}

    # problem checks
    indexer.query.checker:
        class: Phlexible\IndexerComponent\ProblemChecker\QueryChecker
        arguments: ["@indexer.query", "@indexer.search", "@properties"]
        tags:
            - {name: "problem.checker"}

    # assets
    indexer.asset.scripts:
        class: Phlexible\IndexerComponent\Asset\ScriptCollection
        arguments: ["%indexer.asset.script_path%/"]
        tags:
            - {name: "asset.script"}
