parameters:
    phlexible_indexer.result_sorter.relevance.compare_field: ~
    phlexible_indexer.result_sorter.relevance.case_sensitive: ~

services:
    phlexible_indexer.storage_operator:
        class: Phlexible\Bundle\IndexerBundle\Storage\Operation\Operator
        arguments:
            - "@phlexible_queue.job_manager"
            - "@event_dispatcher"

    phlexible_indexer.document_factory:
        class: Phlexible\Bundle\IndexerBundle\Document\DocumentFactory
        arguments:
            - "@event_dispatcher"

    phlexible_indexer.indexers:
        class: Phlexible\Bundle\IndexerBundle\Indexer\IndexerCollection
        arguments: [[]]

    # commands
    phlexible_indexer.command.add_all:
        class: Phlexible\Bundle\IndexerBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: console.command}

    phlexible_indexer.command.add:
        class: Phlexible\Bundle\IndexerBundle\Command\AddCommand
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: console.command}

    phlexible_indexer.command.delete:
        class: Phlexible\Bundle\IndexerBundle\Command\DeleteCommand
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: console.command}

    phlexible_indexer.command.find:
        class: Phlexible\Bundle\IndexerBundle\Command\FindCommand
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: console.command}

    phlexible_indexer.command.index:
        class: Phlexible\Bundle\IndexerBundle\Command\IndexCommand
        arguments:
            - "@phlexible_indexer.storage.default"
        tags:
            - {name: console.command}

    phlexible_indexer.command.status:
        class: Phlexible\Bundle\IndexerBundle\Command\StatusCommand
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: console.command}

    # problem checks
    phlexible_indexer.checker.indexer:
        class: Phlexible\Bundle\IndexerBundle\ProblemChecker\IndexerChecker
        public: false
        arguments:
            - "@phlexible_indexer.indexers"
        tags:
            - {name: phlexible_problem.checker}
