indexer_check_get:
    path: /indexer/check/get/*
    defaults: { module: indexer, controller: check, action: get }
    requirements: { _resource: indexer }

indexer_check_set:
    path: /indexer/check/set/*
    defaults: { module: indexer, controller: check, action: set }
    requirements: { _resource: indexer }

indexer_check:
    path: /indexer/check/check/*
    defaults: { module: indexer, controller: check, action: check }
    requirements: { _resource: indexer }

indexer_search:
    path: /indexer/search/*
    defaults: { module: indexer, controller: search, action: search }
    requirements: { _resource: indexer }
